[package]
name = "lavia-core"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"
ndarray = {version = "0.15", features = ["rayon"]}
ndarray-ndimage = "0.4"
ndarray-rand = "0.14"
rayon = "1.5"
